baseURL = "https://tim.schumacher.im"
title = "Tim Schumacher"
theme = "semantic"
paginate = 4
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = false
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"

[author]
  name = "Tim Schumacher"

[[menu.main]]
  name = "Über mich"
  weight = 20
  identifier = "ueber-mich"
  url = "/ueber-mich/"

[[menu.footer]]
  name = "Über mich"
  weight = 20
  identifier = "ueber-mich"
  url = "/ueber-mich/"